[versions]
antlr = "4.13.2"
junit-jupiter = "6.0.1"
logback-classic = "1.5.23"
slf4j-api = "2.0.17"

kotlin = "2.3.0"
kover = "0.9.4"
ktlint = "14.0.1"
test-logger = "4.0.0"

[libraries]
antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
antlr-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger" }
